version: '3.8'

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: localhost

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      MYSQL_HOST_IP: mysql_db
      STATIC_DOG: 8
      HOST: mysql_db
      USER: root
      DATABASE: doglogic
      DOCKER: "true"
    ports:
      - 9000:9000

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 8000:8000

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8080:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
